version: "3"

services:
  log:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    command: ["udp://logsNNN.papertrailapp.com:YYZZX"]
